[package]
name = "preferz-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
euclid = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
undo = { workspace = true }

